import StyleDictionary from 'style-dictionary';

function cssVariableName(path) {
  if (path[0] === 'primitives') {
    return `--_gw-${path.slice(1).join('-')}`;
  }

  if (path[0] === 'dark') {
    return `--${path.slice(1).join('-')}`;
  }

  return `--${path.join('-')}`;
}

function tokenPath(token) {
  if (Array.isArray(token.path)) {
    return token.path;
  }

  return String(token.name).split('-');
}

function originalValue(token) {
  const original = token.original ?? token;
  const value = original.value ?? original.$value ?? token.value ?? token.$value;
  return String(value);
}

function tokenValue(token, pathToVariableName) {
  const rawValue = originalValue(token);
  return rawValue.replaceAll(/\{([^}]+)\}/g, (_match, referencePath) => {
    const variableName = pathToVariableName.get(String(referencePath));
    if (variableName === undefined) {
      throw new Error(`Unknown token reference: ${referencePath}`);
    }

    return `var(${variableName})`;
  });
}

StyleDictionary.registerFormat({
  name: 'groundwork/css-variables',
  format({ dictionary }) {
    const tokens = dictionary.allTokens;
    const pathToVariableName = new Map(
      tokens.map((token) => [tokenPath(token).join('.'), cssVariableName(tokenPath(token))]),
    );

    const rootTokens = tokens.filter((token) => tokenPath(token)[0] !== 'dark');
    const darkTokens = tokens.filter((token) => tokenPath(token)[0] === 'dark');

    const rootLines = rootTokens.map((token) => {
      const path = tokenPath(token);
      return `  ${cssVariableName(path)}: ${tokenValue(token, pathToVariableName)};`;
    });

    const darkLines = darkTokens.map((token) => {
      const path = tokenPath(token);
      return `    ${cssVariableName(path)}: ${tokenValue(token, pathToVariableName)};`;
    });

    return [
      '/* ============================================================',
      '   GENERATED TOKEN FOUNDATION',
      '   Source: DTCG-format tokens in tokens/primitives.json and tokens/semantic.json',
      '   Do not edit this file directly.',
      '   ============================================================ */',
      '',
      ':root {',
      ...rootLines,
      '}',
      '',
      '@media (prefers-color-scheme: dark) {',
      '  :root {',
      ...darkLines,
      '  }',
      '}',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/primitives.json', 'tokens/semantic.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/generated/',
      files: [
        {
          destination: 'tokens.css',
          format: 'groundwork/css-variables',
        },
      ],
    },
  },
};
