import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import StyleDictionary from 'style-dictionary';

/*
 * Multi-theme token build.
 *
 * Each theme is the shared two-tier source (primitives + semantic mapping) with an
 * optional brand delta merged on top. The default theme is emitted on :root; every
 * other brand is emitted under [data-gw-theme="<name>"] by rewriting the :root selector
 * the formatter produces. Light/dark stays driven by prefers-color-scheme, per brand.
 *
 * A brand delta (tokens/themes/<name>.json) overrides whole primitive ramps and/or a
 * handful of semantic mappings (fonts, leading, border, action-text…). It never touches
 * component CSS — that is the whole point of the exercise.
 */

const BASE_SOURCES = ['tokens/primitives.json', 'tokens/semantic.json'];

const BRANDS = ['warm-editorial', 'precision', 'confident', 'technical', 'solid', 'midnight'];

const THEMES = [
  { name: 'default', selector: ':root', delta: undefined },
  ...BRANDS.map((name) => ({
    name,
    selector: `[data-gw-theme="${name}"]`,
    delta: `tokens/themes/${name}.json`,
  })),
];

function cssVariableName(path) {
  if (path[0] === 'primitives') {
    return `--_gw-${path.slice(1).join('-')}`;
  }

  if (path[0] === 'dark') {
    return `--${path.slice(1).join('-')}`;
  }

  return `--${path.join('-')}`;
}

function tokenPath(token) {
  if (Array.isArray(token.path)) {
    return token.path;
  }

  return String(token.name).split('-');
}

function originalValue(token) {
  const original = token.original ?? token;
  const value = original.value ?? original.$value ?? token.value ?? token.$value;
  return String(value);
}

function tokenValue(token, pathToVariableName) {
  const rawValue = originalValue(token);
  return rawValue.replaceAll(/\{([^}]+)\}/g, (_match, referencePath) => {
    const variableName = pathToVariableName.get(String(referencePath));
    if (variableName === undefined) {
      throw new Error(`Unknown token reference: ${referencePath}`);
    }

    return `var(${variableName})`;
  });
}

StyleDictionary.registerFormat({
  name: 'groundwork/css-variables',
  format({ dictionary }) {
    const tokens = dictionary.allTokens;
    const pathToVariableName = new Map(
      tokens.map((token) => [tokenPath(token).join('.'), cssVariableName(tokenPath(token))]),
    );

    const rootTokens = tokens.filter((token) => tokenPath(token)[0] !== 'dark');
    const darkTokens = tokens.filter((token) => tokenPath(token)[0] === 'dark');

    const rootLines = rootTokens.map(
      (token) => `  ${cssVariableName(tokenPath(token))}: ${tokenValue(token, pathToVariableName)};`,
    );
    const darkLines = darkTokens.map(
      (token) => `    ${cssVariableName(tokenPath(token))}: ${tokenValue(token, pathToVariableName)};`,
    );

    return [
      ':root {',
      ...rootLines,
      '}',
      '',
      '@media (prefers-color-scheme: dark) {',
      '  :root {',
      ...darkLines,
      '  }',
      '}',
    ].join('\n');
  },
});

const TMP_DIR = 'src/styles/generated/.tmp';

async function buildTheme(theme) {
  const sd = new StyleDictionary({
    source: [...BASE_SOURCES, ...(theme.delta ? [theme.delta] : [])],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: `${TMP_DIR}/`,
        files: [{ destination: `${theme.name}.css`, format: 'groundwork/css-variables' }],
      },
    },
    log: { verbosity: 'silent', warnings: 'disabled' },
  });

  await sd.buildAllPlatforms();

  const raw = (await readFile(`${TMP_DIR}/${theme.name}.css`, 'utf8')).trimEnd();
  return theme.selector === ':root' ? raw : raw.replaceAll(':root', theme.selector);
}

const banner = `/* ============================================================
   GENERATED TOKEN FOUNDATION
   Source: DTCG-format tokens in tokens/primitives.json, tokens/semantic.json,
   and the brand deltas in tokens/themes/.
   Built by scripts/build-tokens.mjs. Do not edit this file directly.
   ============================================================ */`;

const blocks = await Promise.all(THEMES.map(buildTheme));

await rm(TMP_DIR, { recursive: true, force: true });
await mkdir('src/styles/generated', { recursive: true });
await writeFile('src/styles/generated/tokens.css', `${banner}\n\n${blocks.join('\n\n')}\n`, 'utf8');
