import { mkdir, readFile, writeFile } from 'node:fs/promises';

const sourceFiles = [
  'src/styles/generated/tokens.css',
  'src/styles/reset.css',
  'src/styles/base.css',
  'src/styles/layout.css',
  'src/styles/typography.css',
  'src/styles/components.css',
  'src/styles/utilities.css',
];

const chunks = await Promise.all(sourceFiles.map((path) => readFile(path, 'utf8')));

const banner = `/*!
 * Groundwork Design System
 * Generated by npm run build:css.
 * Do not edit this file directly.
 */`;

await mkdir('css', { recursive: true });
await writeFile('css/groundwork.css', `${banner}\n\n${chunks.join('\n')}`, 'utf8');
